### PR TITLE
Revert "[IMP] requeriments: Specific the version in the lib to avoid warning"

### PR DESCRIPTION
**Pull request by luisg123v**
Reverts Vauxoo/account-financial-tools#15

Pinned version of `numpy` doesn't work anymore with recent versions of `pandas`:  
`pandas 1.1.0 requires numpy>=1.15.4, but you'll have numpy 1.14.5 which is incompatible.`

In addition, the version the OCA uses is not pinned.

Dummy MR: https://git.vauxoo.com/vauxoo/lodi/-/merge_requests/196

### CODE REVIEW

**Comment by luisg123v** [comment]
@luistorresm could you approve, please?

In addition, do you remember on which circunstances you experienced the warning mentioned on the original PR?

CC @moylop260 @dsabrinarg

**Comment by luisg123v** [comment]
CC @hugho-ad

**Review by hugho-ad — APPROVED** [review]
LGTM :+1: 
image

**Comment by luisg123v** [comment]
Thanks @hugho-ad. I will merge myself to be able to set the commit message correctly.

**Pull request merged**
